replaced libft

diff --git a/libft/Makefile b/libft/Makefile
--- a/libft/Makefile
+++ b/libft/Makefile
@@ -1,20 +1,110 @@
-NAME = libft.a
+# **************************************************************************** #
+#                                                                              #
+#                                                         :::      ::::::::    #
+#    Makefile                                           :+:      :+:    :+:    #
+#                                                     +:+ +:+         +:+      #
+#    By: jmertane <jmertane@student.hive.fi>        +#+  +:+       +#+         #
+#                                                 +#+#+#+#+#+   +#+            #
+#    Created: 2023/10/28 10:37:44 by jmertane          #+#    #+#              #
+#    Updated: 2024/03/26 19:42:01 by jmertane         ###   ########.fr        #
+#                                                                              #
+# **************************************************************************** #
 
-CFILES = ft_atoi.c ft_bzero.c ft_calloc.c ft_isalnum.c ft_isalpha.c ft_isascii.c ft_isdigit.c ft_isprint.c ft_memchr.c ft_memcpy.c ft_memmove.c ft_memcmp.c ft_memset.c ft_strchr.c ft_strdup.c ft_strlcat.c ft_strlcpy.c ft_strlen.c ft_strncmp.c ft_strnstr.c ft_strrchr.c ft_tolower.c ft_toupper.c ft_substr.c ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c ft_striteri.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c
-OFILES = ${CFILES:.c=.o}
+NAME		:=	libft.a
+OBJSDIR		:=	build
+DEPSDIR		:=	.deps
+ERRORTXT	:=	error.txt
 
-all: ${NAME}
+CC			:=	cc
+RM			:=	rm -rf
+AR			:=	ar -rcs
+CFLAGS		:=	-Wall -Werror -Wextra
+DEPFLAGS	=	-c -MT $@ -MMD -MP -MF $(DEPSDIR)/$*.d
 
-${NAME}: ${OFILES}
-	ar rc ${NAME} ${OFILES}
+FILES		:= 	ft_isalpha \
+				ft_isdigit \
+				ft_isalnum \
+				ft_isascii \
+				ft_isprint \
+				ft_bzero \
+				ft_calloc \
+				ft_memset \
+				ft_memcpy \
+				ft_memmove \
+				ft_memchr \
+				ft_memcmp \
+				ft_putchar_fd \
+				ft_putstr_fd \
+				ft_putendl_fd \
+				ft_putnbr_fd \
+				ft_strlen \
+				ft_strlcpy \
+				ft_strlcat \
+				ft_strchr \
+				ft_strrchr \
+				ft_strncmp \
+				ft_strnstr \
+				ft_strdup \
+				ft_substr \
+				ft_strjoin \
+				ft_strtrim \
+				ft_split \
+				ft_atoi \
+				ft_itoa \
+				ft_toupper \
+				ft_tolower \
+				ft_strmapi \
+				ft_striteri \
+				ft_printf \
+				ft_printf_fmt \
+				get_next_line \
+				get_next_line_utils
 
-${OFILES}: ${CFILES}
-	cc -Wall -Wextra -Werror -c ${CFILES} -I libft.h
+HEADERS		:=	libft \
+				ft_printf \
+				get_next_line
+
+SRCS		:=	$(addsuffix .c, $(FILES))
+SRCS		+=	$(addsuffix .h, $(HEADERS))
+OBJS		=	$(patsubst %.c, $(OBJSDIR)/%.o, $(SRCS))
+DEPS		=	$(patsubst %.c, $(DEPSDIR)/%.d, $(SRCS))
+
+F			=	=================================================
+B			=	\033[1m
+T			=	\033[0m
+G			=	\033[32m
+V			=	\033[35m
+C			=	\033[36m
+R			=	\033[31m
+Y			=	\033[33m
+
+all: $(NAME)
+
+$(NAME): $(OBJS)
+	@$(AR) $(NAME) $(OBJS)
+
+$(OBJSDIR)/%.o: %.c | $(OBJSDIR) $(DEPSDIR)
+	@if ! $(CC) $(CFLAGS) $(DEPFLAGS) $< -o $@ 2> $(ERRORTXT); then \
+		echo "$(R)$(B)\nMAKEFILE TERMINATED!\n$(F)$(T)\n"; \
+		echo "$(V)Unable to create object file: $(R)$(B)$@$(T)\n"; \
+		echo "$(Y)$(B)ERROR\t>>>>>>>>$(T)$(Y)\n"; sed '$$d' $(ERRORTXT); \
+		echo "$(R)$(B)\n$(F)\nExiting...$(T)\n"; exit 1 ; fi
+	@if [ ! $(CNTR) ]; then \
+		$(eval CNTR=$(shell echo $$(($(CNTR)+1)))) \
+		echo "\n$(V)Building $(G)$(B)$(NAME)$(T)$(V) binary...$(T)"; fi
 
 clean:
-	rm -f ${OFILES}
+	@$(RM) $(OBJSDIR) $(DEPSDIR) $(ERRORTXT)
 
 fclean: clean
-	rm -f ${NAME}
+	@$(RM) $(NAME)
 
 re: fclean all
+
+$(OBJSDIR) $(DEPSDIR):
+	@mkdir -p $@
+
+$(DEPS):
+	include $(wildcard $(DEPS))
+
+.PHONY: all clean fclean re
