Restructured libft and updated both Makefiles. Updated Makefiles to use depflags

diff --git a/libft/Makefile b/libft/Makefile
--- a/libft/Makefile
+++ b/libft/Makefile
@@ -6,25 +6,31 @@
 #    By: jmertane <jmertane@student.hive.fi>        +#+  +:+       +#+         #
 #                                                 +#+#+#+#+#+   +#+            #
 #    Created: 2023/10/28 10:37:44 by jmertane          #+#    #+#              #
-#    Updated: 2024/05/06 15:25:56 by jmertane         ###   ########.fr        #
+#    Updated: 2024/05/06 19:56:58 by jmertane         ###   ########.fr        #
 #                                                                              #
 # **************************************************************************** #
 
 NAME		:=	libft.a
-OBJSDIR		:=	objs
+ERRTXT		:=	error.txt
+OBJSDIR		:=	build
 INCSDIR		:=	incs
 SRCSDIR		:=	srcs
 DEPSDIR		:=	.deps
-ERRORTXT	:=	error.txt
 
-CC			:=	cc
 RM			:=	rm -rf
 AR			:=	ar -rcs
+CC			:=	cc
 CFLAGS		:=	-Wall -Werror -Wextra
-DEPFLAGS	=	-c -MT $@ -MMD -MP -MF $(DEPSDIR)/$*.d
+DEBUGFLAGS	=	-g -fsanitize=address
+DEPFLAGS	=	-c -MT $$@ -MMD -MP -MF $(DEPSDIR)/$$*.d
+SCREENCLR	:=	printf "\033c"
 SLEEP		:=	sleep .1
 
-FILES		:= 	ft_isalpha.c \
+MODULES		:=	libft \
+				printf \
+				gnl
+
+SOURCES		:= 	ft_isalpha.c \
 				ft_isdigit.c \
 				ft_isalnum.c \
 				ft_isascii.c \
@@ -61,15 +67,17 @@ FILES		:= 	ft_isalpha.c \
 				ft_printf.c \
 				ft_printf_fmt.c \
 				ft_gnl.c \
-				ft_gnl_utils.c
+				ft_gnl_utils.c \
 
-SRCS		=	$(addprefix $(SRCSDIR)/, $(FILES))
-OBJS		=	$(patsubst $(SRCSDIR)/%.c, $(OBJSDIR)/%.o, $(SRCS))
-DEPS		=	$(patsubst $(SRCSDIR)/%.c, $(DEPSDIR)/%.d, $(SRCS))
+SOURCEDIR	:=	$(addprefix $(SRCSDIR)/, $(MODULES))
+BUILDDIR	:=	$(addprefix $(OBJSDIR)/, $(MODULES))
+DEPENDDIR	:=	$(addprefix $(DEPSDIR)/, $(MODULES))
+SRCS		:=	$(foreach file, $(SOURCES), $(shell find $(SOURCEDIR) -name $(file)))
+OBJS		:=	$(patsubst $(SRCSDIR)/%.c, $(OBJSDIR)/%.o, $(SRCS))
+DEPS		:=	$(patsubst $(SRCSDIR)/%.c, $(DEPSDIR)/%.d, $(SRCS))
+INCS	 	:=	$(foreach header, $(INCSDIR), -I $(header))
 
-INCS 		=	$(foreach dir, $(INCSDIR), -I $(dir))
-
-F			=	============================================================
+F			=	=====================================
 B			=	\033[1m
 T			=	\033[0m
 G			=	\033[32m
@@ -78,45 +86,57 @@ C			=	\033[36m
 R			=	\033[31m
 Y			=	\033[33m
 
+vpath %.c $(SOURCEDIR)
+
+define cc_cmd
+$1/%.o: %.c | $(BUILDDIR) $(DEPENDDIR)
+	@if ! $(CC) $(CFLAGS) $(INCS) $(DEPFLAGS) $$< -o $$@ 2> $(ERRTXT); then \
+		printf "$(R)$(B)\nERROR!\n$(F)$(T)\n"; \
+		printf "$(V)Unable to create object file:$(T)\n\n"; \
+		printf "$(R)$(B)$$@$(T)\n"; \
+		printf "$(Y)\n"; sed '$$d' $(ERRTXT); \
+		printf "$(R)$(B)\n$(F)\nExiting...$(T)\n"; exit 1 ; \
+	else \
+		printf "$(C)$(B)☑$(T)$(V) $$<$ \n    $(C)⮑\t$(G)$(B)$$@$(T) \t\n"; \
+	fi
+endef
+
 all: $(NAME)
 
 $(NAME): $(OBJS)
-	@$(AR) $(NAME) $(OBJS) && $(SLEEP)
-	@printf "$(V)\nSuccessfully compiled binary $(G)$(B)$(NAME)$(T)"
-	@printf "$(V) and $(G)$(B)$(CNTR)$(V) object file(s).$(T)\n"
-	@printf "$(G)$(B)\n$(F)$(T)\n\n"
+	@$(AR) $@ $^
+	@make finish
 
-$(OBJSDIR)/%.o: $(SRCSDIR)/%.c | $(OBJSDIR) $(DEPSDIR)
-	@if ! $(CC) $(CFLAGS) $(INCS) $(DEPFLAGS) $< -o $@ 2> $(ERRORTXT); then \
-		echo "$(R)$(B)\nMAKE TERMINATED!\n$(F)$(T)\n"; \
-		echo "$(V)Unable to create object file: $(R)$(B)$@$(T)\n"; \
-		echo "$(Y)$(B)ERROR\t>>>>>>>>$(T)$(Y)\n"; sed '$$d' $(ERRORTXT); \
-		echo "$(R)$(B)\n$(F)\nExiting...$(T)\n"; exit 1 ; fi
-	@if [ $(CNTR) ]; then \
-		$(eval CNTR=$(shell echo $$(($(CNTR)+1)))) \
-		printf "✅$(T)$(V) $<$(T) $(C)       \t🔀\t$(G)$(B)$@$(T)\n"; else \
-		make title; printf "✅$(T)$(V) $<$(T) $(C)       \t🔀\t$(G)$(B)$@$(T)\n"; fi
-
-title:
-	@printf "$(C)                         $(R)$(B)                            ╱|、$(T)\n"
-	@printf "$(C)╦  ╦╔╗ ╔═╗╔╦╗            $(R)$(B)                           (˚ˎ 。7$(T)\n"
-	@printf "$(C)║  ║╠╩╗╠╣  ║             $(R)$(B)                           |、˜〵$(T)\n"
-	@printf "$(C)╩═╝╩╚═╝╚   ╩  by jmertane$(R)$(B)                           じしˍ,)ノ$(T)\n"
-	@printf "$(G)$(B)$(F)\n$(T)\n"
-	@printf "$(V)Using compiler $(G)$(B)$(CC)$(T)$(V) with flags: $(G)$(B)$(CFLAGS)$(T)\n\n"
+debug: CFLAGS += $(DEBUGFLAGS)
+debug: all
 
 clean:
-	@$(RM) $(OBJSDIR) $(DEPSDIR) $(ERRORTXT)
+	@$(RM) $(OBJSDIR) $(DEPSDIR) $(ERRTXT)
 
 fclean: clean
 	@$(RM) $(NAME)
 
 re: fclean all
 
-$(OBJSDIR) $(DEPSDIR):
+title:
+	@$(SCREENCLR) && printf "\n"
+	@printf "$(C)╦  ╦╔╗ ╔═╗╔╦╗$(T)\n"
+	@printf "$(C)║  ║╠╩╗╠╣  ║ $(T)\n"
+	@printf "$(C)╩═╝╩╚═╝╚   ╩             by jmertane$(T)\n"
+	@printf "$(G)$(B)$(F)\n$(T)\n"
+
+finish:
+	@printf "\n$(G)$(B)$(F)$(T)\n"
+	@printf "$(C)╔═╗╦╔╗╔╦╔═╗╦ ╦╔═╗╔╦╗          $(V)$(B)$(NAME)$(T)\n"
+	@printf "$(C)╠╣ ║║║║║╚═╗╠═╣║╣  ║║$(T)\n"
+	@printf "$(C)╚  ╩╝╚╝╩╚═╝╩ ╩╚═╝═╩╝$(T)\n\n"
+
+$(BUILDDIR) $(DEPENDDIR):
 	@mkdir -p $@
 
 $(DEPS):
 	include $(wildcard $(DEPS))
 
-.PHONY: all clean fclean re title
+$(foreach build, $(BUILDDIR), $(eval $(call cc_cmd, $(build))))
+
+.PHONY: all debug clean fclean re title finish
